Make compile options private
jaegertracing/jaeger-client-cpp pull request #175
Opened 2019-09-19 11:29 UTC by FredrikAppelros

##  Which problem is this PR solving?
The CMake configuration pollutes the compiler options of projects that include the Jaeger headers. This results in the same warning options that are enabled for this project to leak into other projects, causing problems when integrating Jaeger with codebases that cannot be cleanly compiled using the same options.

## Short description of the changes

Since the changes introduced by 7e9a135b362c47f7e4d42e0693b05b91a70e6888 the Jaeger internal compiler options are propagated to projects that depend on the Jaeger headers.

Since these options are not strictly necessary to build Jaeger and are only added to make sure that warnings are emitted for this project, they could instead be made private. This avoids polluting other projects with the internal Jaeger compiler options.

2019-09-20 17:13 UTC, yurishkuro approved these changes

2019-09-20 17:13 UTC, yurishkuro commented
@mdouaihy I am not familiar w/ cmake, does this change look ok?

2019-09-20 18:39 UTC, mdouaihy requested changes
Since these options does not break the ABI, it should be safe to make them private.

@FredrikAppelros, I think we should also add them to the unit tests and the testutils.

Also, it would be great if you add a comment stating that these flags should not contain an ABI breaker flag.

2019-09-29 20:51 UTC, mdouaihy commented
@FredrikAppelros, sorry for  my late reply.

- for the compilation flags into the UniTest target, my point is that, before, those flags were inherited by all targets because they were public. Making them private means that they are no more defined for the UnitTest and I believe they can be useful for these artifacts
- As for the comment, it's important that these flags dont impact the ABI. Having a comment does not prevent that but can be helpful

2020-03-03 07:22 UTC, mdouaihy commented
@FredrikAppelros, do you have any updates on this change?

2020-07-03 15:29 UTC, mdouaihy commented
@FredrikAppelros, do you have any updates on this change?

2022-01-10 19:40 UTC, closed without merging